version: '3.4'

volumes:
  poptape_categories_data:
    name: poptape_categories_data

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/categories/api:v0.1
    ports:
      - "1260:8220"
    restart: "always"
    depends_on:
      - db
    networks:
      - net_poptape
  db:
    image: postgres:alpine
    restart: "always"
    ports:
      - "1261:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - poptape_categories_data:/var/lib/postgresql/data
    networks:
      - net_poptape
networks:
  net_poptape:
    external: true

  
